---
apiVersion: v1
kind: Secret
metadata:
  name: caddy-tls
  namespace: caddy-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    REPLACE_WITH_TLS_CERT_PEM
  tls.key: |
    REPLACE_WITH_TLS_KEY_PEM
