---
apiVersion: v1
kind: Secret
metadata:
  name: authelia-secrets
  namespace: authelia
type: Opaque
stringData:
  AUTHELIA_JWT_SECRET: "REPLACE_WITH_JWT_SECRET"
  AUTHELIA_SESSION_SECRET: "REPLACE_WITH_SESSION_SECRET"
  AUTHELIA_STORAGE_ENCRYPTION_KEY: "REPLACE_WITH_ENCRYPTION_KEY"
