apiVersion: v1
kind: Service
metadata:
  name: agentic-offering
  namespace: apps
  labels:
    app: agentic-offering
    env: exp
spec:
  type: ClusterIP
  selector:
    app: agentic-offering
    env: exp
  ports:
    - port: 3020
      targetPort: 3020
      protocol: TCP
